#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=1
#PBS -N 2017_cr_nojoin_no_golay_serial
#PBS -A d411-training

cd $PBS_O_WORKDIR

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

#load modules and qiime
module load miniconda/python2

#loading virtualenv
echo "loading virtualenv"

source activate qiime1

biom summarize-table -i ~/otus/otu_table.biom -o otus.txt
