#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2017_cr_nojoin_no_golay_serial
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv" 

source activate qiime1

compare_categories.py --method anosim -i ~/2018_02_smb/core_output2/bdiv_even627/weighted_unifrac_dm.txt -m ~/2018_02_smb/map.tsv -c SampleNitrogen -o anosim_output_N_w -n 99

source deactivate
